name: coex
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pytorch-lightning=1.4.0
  - ruamel.yaml
  - pillow
  - scikit-image
  - pip:
    - opencv-contrib-python
    - albumentations
    - timm
    - test-tube