name: coex
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit
  - ruamel.yaml
  - pillow
  - scikit-image
  - pip:
    - pytorch-lightning
    - opencv-contrib-python
    - albumentations
    - timm
    - test-tube
    # - --find-links https://github.com/pytorch/TensorRT/releases
    # - torch-tensorrt
