name: coex
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.7
  - anaconda
  - pip
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit=11.1
  - pytorch-lightning
  - ruamel.yaml
  - pillow
  - scikit-image
  - pip:
    - opencv-contrib-python
    - albumentations
    - timm
    - test-tube